### ISSUE TITLE
Can anyone run a Ronin node?

### ISSUE THREAD

**Issue by mehranhydary** [axieinfinity/ronin-manager#12]
If so - how would I get started? The reason I want to run a Ronin node is so that I can deploy smart contracts on the Ronin network.

Thanks!

**Comment by feveral** [comment]
1. You should first install Rust and Cargo
2. `cp config/test.env .env` for testnet or `cp config/main.env .env` for mainnet
3. In `.env`, `INSTANCE_NAME`, `VALIDATOR_PRIVATE_KEY` and `ETHEREUM_ENDPOINT` should be given
4. Then run `./bin/package.sh`
5. You will get a tar file like `pkg-linux-v0.7.0-5e789f.tar.gz`
6. Unzip it `tar zxvf pkg-linux-v0.7.0-5e789f.tar.gz`
7. Put your .env file into the unziped folder `cp .env pkg-ronin-manager-0.7.0/`

Please correct me if there is anything wrong

**Comment by buihongduc132** [comment]
Just wondering, we can run it, but do we allowed to run it?

**Comment by feveral** [comment]
Why not, it's blockchain world

**Comment by rogerioaguas** [comment]
Hi @feveral , where can i found the `VALIDATOR_PRIVATE_KEY`, `ETHEREUM_ENDPOINT`? 
In the `INSTANCE_NAME` can i use anything?

thanks!

**Comment by buihongduc132** [comment]
> Why not, it's blockchain world
@feveral 
They tend to restrict usage to almost everything. And blacklist your assets our of Skymavis service. This is what I am concern. 
Btw, congratz on your node showing up on the explorer 👍 

@rogerioaguas 
`VALIDATOR_PRIVATE_KEY`: generate a private key and use it, you can use web3. 
`ETHEREUM_ENDPOINT`: using some provider like infura or alchemy.
`INSTANCE_NAME`: anything.

**Comment by trungfinity** [comment]
@mehranhydary @feveral Ronin is currently running the Proof-of-Authority consensus. People can run their own node (for querying and verifying the correctness of data) but cannot be a validator (yet) (for producing blocks) until Ronin is ready for wider use. Deploying contracts is also limited to allowed addresses.

@buihongduc132 Ronin and Axie Infinity follow different governance and should not be put together using vague words to spread misleading information.

Axie Infinity games—which are services provided by Sky Mavis, a party not the owner of the Axie Infinity ecosystem—have their own Terms of Use, which you could find here (https://axieinfinity.com/terms). Sky Mavis has full rights to reject those who violate the terms to continue using its services.

Core logics of Axie Infinity, especially ownership, belong to the Axie Infinity ecosystem, are on-chain and protected by the immutability of the blockchain. No one can restrict them.

@mehranhydary We for sure will announce to people when Ronin is ready. Stay tuned!

**Comment by mehranhydary** [comment]
Thanks for the update @trungfinity !
